# docker/Dockerfile
FROM node:20-alpine

WORKDIR /app

RUN apk update && apk upgrade && apk add --no-cache bash

# Copia package.json e package-lock.json do backend
COPY ../coursekeeper-backend/package*.json ./
RUN npm ci

# Copia todo o backend
COPY ../coursekeeper-backend ./

# Gera Prisma Client
RUN npx prisma generate --schema=prisma/schema.prisma

# Build do Nest
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
